FROM debian:bookworm-slim

# nc + curl + mc
RUN apt-get update \
 && apt-get install -y curl netcat-openbsd \
 && curl -L https://dl.min.io/client/mc/release/linux-amd64/mc \
      -o /usr/local/bin/mc \
 && chmod +x /usr/local/bin/mc \
 && rm -rf /var/lib/apt/lists/*

COPY wait-for-minio.sh /wait-for-minio.sh
RUN chmod +x /wait-for-minio.sh

CMD ["/wait-for-minio.sh"]
