services:
  iiif-minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    container_name: iiif-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - miniidata:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks: [cant]

  iiif-minio-buckets:
    build:
      context: .
      dockerfile: Dockerfile.minio-buckets
    depends_on: [iiif-minio]
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    networks: [cant]

  iiif-cantaloupe:
    image: cantaloupe-cantaloupe            # ton image déjà construite
    container_name: iiif-cantaloupe
    depends_on: [iiif-minio, iiif-minio-buckets]
    ports:
      - "8000:80"
    volumes:
      - ./cantaloupe.properties:/etc/cantaloupe.properties:ro
      - ./lookup.rb:/etc/lookup.rb:ro
    networks: [cant]

volumes:
  miniidata:

networks:
  cant:
